export const GET_ALL_BREEDS = 'GET_ALL_BREEDS'
export const GET_ALL_BREEDS_SUCCESS = 'GET_ALL_BREEDS_SUCCESS'
export const GET_ALL_BREEDS_ERROR = 'GET_ALL_BREEDS_ERROR'

export const GET_RANDOM_BREEDS = 'GET_RANDOM_BREEDS'
export const GET_RANDOM_BREEDS_SUCCESS = 'GET_RANDOM_BREEDS_SUCCESS'
export const GET_RANDOM_BREEDS_ERROR = 'GET_RANDOM_BREEDS_ERROR'

export const GET_SEARCHED_BREED = 'GET_SEARCHED_BREED'
export const GET_SEARCHED_BREED_SUCCESS = 'GET_SEARCHED_BREED_SUCCESS'
export const GET_SEARCHED_BREED_ERROR = 'GET_SEARCHED_BREED_ERROR'

export const GET_SUB_BREEDS_SUCCESS = 'GET_SUB_BREEDS_SUCCESS'

export const GET_SUB_BREED_DATA_SUCCESS = 'GET_SUB_BREED_DATA_SUCCESS'

export const SEARCH_BREED = 'SEARCH_BREED'
export const REMOVE_SEARCHED_BREED = 'REMOVE_SEARCHED_BREED'

export const SAVE_DOG = 'SAVE_DOG'

export const GET_FILTERED_BREED_DATA = 'GET_FILTERED_BREED_DATA'
